/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Admin {
  issueKey(ttlSeconds: number, label?: string | undefined | null): Promise<JsIssuedKey>
  /**
   * Temporary credentials. Pages through the whole inventory when neither
   * argument is given, matching `listServices` and `listConnections`; a
   * truncated credential list with no way to see that it was truncated is
   * worse than a slower call. Pass `page` to fetch exactly one page.
   */
  listKeys(page?: number | undefined | null, pageSize?: number | undefined | null): Promise<Array<JsKeyMetadata>>
  revokeKey(keyId: number): Promise<JsKeyMetadata>
  showKey(keyId: number): Promise<JsIssuedKey>
  revealKey(keyId: number): Promise<JsIssuedKey>
  renewKey(keyId: number, ttlSeconds: number): Promise<JsIssuedKey>
  gcKeys(): Promise<number>
  resetAuthState(): Promise<void>
  rotateRootKey(newKey?: string | undefined | null): Promise<string>
  authStatus(): Promise<JsAuthStatus>
  setLegacyProtocol(policy: string): Promise<void>
  listServices(keyId?: number | undefined | null): Promise<Array<JsServiceInfo>>
  listConnections(keyId?: number | undefined | null): Promise<Array<JsConnectionInfo>>
}

export declare class Client {
  constructor(config: JsClientConfig)
  server(): string
  register(request: JsRegisterRequest): Promise<Registration>
  connect(request: JsConnectRequest): Promise<Connection>
  listKeys(): Promise<Array<string>>
  serviceStatus(key: string): Promise<Array<JsServiceConnection>>
  remoteId(): Promise<JsRemoteId>
  admin(): Admin
}

/** A live `connect` tunnel: a local listener forwarding to a registered service. */
export declare class Connection {
  /** The service key this tunnel is bound to. */
  key(): string
  /**
   * The tunnel's latest status: `starting`, `connected`, `retrying`,
   * `stopped`, or `failed:<reason>`.
   */
  status(): string
  /**
   * Resolves once the tunnel is connected, and rejects if it fails or
   * is stopped first.
   *
   * Without `timeoutMs` this waits indefinitely, which is only safe
   * because a tunnel the relay refuses permanently settles as failed
   * rather than retrying forever.
   */
  waitReady(timeoutMs?: number | undefined | null): Promise<void>
  /** Cancels the tunnel's worker and waits for it to unwind. */
  stop(): Promise<void>
}

/** A live `register` tunnel: a local service published on the relay. */
export declare class Registration {
  /** The service key this tunnel is bound to. */
  key(): string
  /**
   * The tunnel's latest status: `starting`, `connected`, `retrying`,
   * `stopped`, or `failed:<reason>`.
   */
  status(): string
  /**
   * Resolves once the tunnel is connected, and rejects if it fails or
   * is stopped first.
   *
   * Without `timeoutMs` this waits indefinitely, which is only safe
   * because a tunnel the relay refuses permanently settles as failed
   * rather than retrying forever.
   */
  waitReady(timeoutMs?: number | undefined | null): Promise<void>
  /** Cancels the tunnel's worker and waits for it to unwind. */
  stop(): Promise<void>
}

export interface JsAuthStatus {
  schemaVersion: number
  safeMode: boolean
  capacity: number
  activeKeys: number
  expiredKeys: number
  revokedKeys: number
  legacyProtocol: string
  activeLegacyConnections: number
  /**
   * Unix seconds of the most recent legacy (protocol-v1) connection, or
   * `null` if the server has never seen one.
   */
  lastLegacyConnectionAt?: number
  authSuccesses: number
  authFailures: number
  serverInstanceId: string
}

export interface JsClientConfig {
  server: string
  credential: string
  keepAlive?: boolean
  namespace?: number
}

export interface JsConnectionInfo {
  keyId: number
  namespace: number
  serviceName: string
  connId: number
  generation: number
  protocolVersion: number
  healthy: boolean
  transport: string
  codecEnabled: boolean
  lastRxAgeMs: number
}

export interface JsConnectRequest {
  key: string
  localAddr: string
  transport: string
}

export interface JsIssuedKey {
  keyId: number
  state: string
  issuedAt: number
  expiresAt: number
  label?: string
  credential: string
}

export interface JsKeyMetadata {
  keyId: number
  state: string
  issuedAt: number
  expiresAt: number
  label?: string
}

export interface JsRegisterRequest {
  key: string
  localAddr: string
  transport: string
  codec?: boolean
  forceNamespace?: boolean
}

export interface JsRemoteId {
  serverMap: string
  active: string
  idle: string
}

export interface JsServiceConnection {
  connId: number
  generation: number
  protocolVersion: number
  healthy: boolean
  lastRxAgeMs: number
}

export interface JsServiceInfo {
  keyId: number
  namespace: number
  serviceName: string
  transport: string
  codecEnabled: boolean
  connectionCount: number
}
