[package]
name = "pb-mapper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
socket2 = "0.5.5"
tokio = { version = "1", features = ["full"] }
snafu = "0.7.5"
flume = { version = "0.11.0", default-features = false, features = ["async"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
once_cell = "1.18.0"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = [
    "env-filter",
    "fmt",
], default-features = true }
hashbrown = { version = "0.14.3" }
clap = { version = "4.4.8", features = ["derive"] }
futures = "0.3.30"
mimalloc-rust = "0.2"
bytes = "1.5.0"
trust-dns-resolver = { version = "0.23.2" }
ring = "0.17.8"

[dev-dependencies]
dotenvy = "0.15.7"
