[package]
name = "pb-mapper-server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Relay server implementation for pb-mapper"
documentation = "https://docs.rs/pb-mapper-server"
readme = "README.md"
keywords = ["proxy", "tunnel", "relay", "tcp", "udp"]
categories = ["network-programming"]
publish = ["crates-io"]

[dependencies]
pb-mapper-auth.workspace = true
pb-mapper-core.workspace = true
pb-mapper-protocol.workspace = true

hashbrown.workspace = true
kanal.workspace = true
snafu.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
uni-stream.workspace = true

[dev-dependencies]
rand.workspace = true

[features]
udp-timeout = ["uni-stream/udp-timeout", "pb-mapper-protocol/udp-timeout"]

[lints]
workspace = true
