name: Bug Report
description: Report a reproducible problem to help us fix it quickly.
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve **pb-mapper** 🙌

        Please provide enough detail for maintainers and contributors to reproduce your issue.
  - type: checkboxes
    id: checks
    attributes:
      label: Before You Start
      options:
        - label: I searched existing issues and did not find a duplicate.
          required: true
        - label: I have tested with the latest release when possible.
          required: true
  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Which area is impacted?
      options:
        - pb-mapper-server
        - pb-mapper-server-cli
        - pb-mapper-client-cli
        - Flutter UI
        - Docker / deployment scripts
        - Documentation
        - Other
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: e.g. v0.2.1 (or commit SHA if built from source)
      placeholder: v0.2.1
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: OS, architecture, deployment mode, network context, etc.
      placeholder: |
        - OS: Ubuntu 24.04
        - Arch: x86_64
        - Install: docker / release binary / source build
        - Related env vars: ...
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: Provide exact commands and steps.
      placeholder: |
        1. Start server with ...
        2. Register service with ...
        3. Connect client with ...
        4. Observe ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs / Error Output
      description: Paste relevant logs, stack traces, or screenshots.
      render: shell
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Anything else that might help (workarounds, comparisons, diagrams, links).
    validations:
      required: false
