display_name: pb-mapper
product_name: pb-mapper
description: Network port mapping and tunneling tool
company_name: pb-mapper
copyright: Copyright © 2024 pb-mapper
exe_name: pb_mapper_ui.exe
installer_name: pb-mapper-setup.exe