app_id: 6L913538-42B1-4596-G479-BJ779F21A65D
publisher: lb7666
publisher_url: https://github.com/acking-you/pb-mapper
display_name: pb-mapper
create_desktop_icon: true
setup_icon_file: windows\runner\resources\app_icon.ico
locales:
  - zh
  - en