[package]
name = "pb-mapper-client"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Register, connect, status, and admin client implementation for pb-mapper"

[dependencies]
pb-mapper-auth.workspace = true
pb-mapper-core.workspace = true
pb-mapper-protocol.workspace = true

serde_json.workspace = true
snafu.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
uni-stream.workspace = true

[features]
udp-timeout = ["uni-stream/udp-timeout", "pb-mapper-protocol/udp-timeout"]

[lints]
workspace = true
