display_name: pb-mapper
description: Network port mapping and tunneling tool - Portable Version
company_name: pb-mapper
copyright: Copyright © 2024 pb-mapper
version: 1.0.0
archive_name: pb-mapper-portable.zip

# Include additional files
include_files:
  - source: ../../runner/resources/app_icon.ico
    destination: app_icon.ico

# Documentation files (if they exist)
# include_files:
#   - source: ../../../README.md
#     destination: README.md
#   - source: ../../../LICENSE
#     destination: LICENSE.txt