[package]
# Do not change the name of this crate.
name = "hub"
version = "0.1.0"
edition = "2024"

[lib]
# `lib` is required for non-library targets,
# such as tests and benchmarks.
# `cdylib` is for Linux, Android, Windows, and web.
# `staticlib` is for iOS and macOS.
crate-type = ["lib", "cdylib", "staticlib"]

[lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
wildcard_imports = "deny"

[dependencies]
tracing.workspace = true
tracing-subscriber.workspace = true
rinf = "8.7.2"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0"
dirs = "5.0"
tokio = { version = "1.45.0", features = ["rt", "sync", "time", "macros"] }
tokio-util = "0.7"
tokio_with_wasm = { version = "0.8.5", features = [
    "rt",
    "sync",
    "time",
    "macros",
] }
wasm-bindgen = "0.2.100"
async-trait = "0.1.87"
messages = "0.3.1"
anyhow = "1.0.89"
sample_crate = { path = "../sample_crate" }


pb-mapper = { path = "../../../" }
