name: Build and Push pb-mapper-server Docker Images

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

env:
  REGISTRY: docker.io
  IMAGE_NAME: ackingliu/pb-mapper

permissions:
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - arch: x86_64
            platform: linux/amd64
            suffix: x86_64_musl
          - arch: aarch64
            platform: linux/arm64
            suffix: aarch64_musl
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.88.0
          targets: ${{ matrix.target.arch }}-unknown-linux-musl

      - name: Build pb-mapper-server binary
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --bin pb-mapper-server --verbose --release --target ${{ matrix.target.arch }}-unknown-linux-musl

      - name: Prepare files for Docker build
        run: |
          # Copy binary to expected location for Docker build
          mkdir -p target/release
          cp target/${{ matrix.target.arch }}-unknown-linux-musl/release/pb-mapper-server target/release/
          cp scripts/release/entrypoint/pb-mapper-server.sh target/release/

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch,suffix=-${{ matrix.target.suffix }}
            type=ref,event=tag,suffix=-${{ matrix.target.suffix }}
            type=semver,pattern={{version}},suffix=-${{ matrix.target.suffix }}
            type=semver,pattern={{major}}.{{minor}},suffix=-${{ matrix.target.suffix }}
            type=semver,pattern={{major}},suffix=-${{ matrix.target.suffix }}
            type=raw,value=latest,suffix=-${{ matrix.target.suffix }},enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/pb-mapper-server.dockerfile
          platforms: ${{ matrix.target.platform }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Update Docker Hub description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ackingliu/pb-mapper
          short-description: "pb-mapper network tunneling server - expose local services through a public server"
          readme-filepath: ./DOCKER_README.md